---
title: "COVID-19 SR Visualisation in R"
author: Tatjana Kecojevic
date: '2020-02-24'
slug: programme
categories: []
tags:
  - rststs
  - covid19
  - corona
comments: yes
image: ''
menu: ''
share: yes
---

This R project is a joint effort of [Sister Analyst](https://sisteranalyst.org/) team: 

- [Anđela Milivojević](https://www.linkedin.com/in/andjela-milivojevic/),
- [Tijana Blagojev](https://www.linkedin.com/in/tijana-blagojev-288b3442/), 
- [Jovana Savić](https://www.linkedin.com/in/jovana-savi%C4%87-12aa305a/), 
- [Katarina Kosimina](https://www.linkedin.com/in/kosmina/) and 
- [Tatjana Kecojević](https://www.linkedin.com/in/tatjana-kecojevic-803704143/). 


Sisters is action 🙌💜

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = F,
                      include=TRUE,
                      prompt = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height = 5,
                      fig.width = 7,
                      cache = FALSE)
```


```{r,  echo=FALSE}
library(ggplot2)
library(gganimate)
library(gapminder)
library(dplyr)

#=================================================================

srdata <- read.csv("covid19SR_tidy.csv", fileEncoding = "UTF-8")

#=================================================================
data_plot <- srdata %>% 
  filter(Total != 0) %>% 
  group_by(Town)

data_plotBG <- data_plot %>% 
  filter(Town == "BEOGRAD")

ggplot(data_plot, aes(Day, Total, group = Town)) + 
  geom_line() + 
  geom_segment(aes(xend = max(Day) + 7, yend = Total), linetype = 2, colour = 'grey') + 
  geom_point(size = 0.5, col = "red") + 
  geom_text(aes(x = max(Day) + 1.5, label = Town), hjust = 0) + 
  scale_x_continuous(breaks = seq(6, 25, 1), labels = seq(6, 25, 1)) +
  transition_reveal(Day) + 
  coord_cartesian(clip = 'off') + 
  labs(title = 'COVID-19 SR', y = 'Total Number', x = "March") + 
  theme_minimal() + 
  theme(plot.margin = margin(5.5, 40, 5.5, 5.5))
```

```{r, echo=FALSE}
maxT <- max(data_plot$Total)

ggplot(data_plot, aes(x = Town, y = Total, fill = Town)) +
  geom_hline(yintercept = 0.05, colour = "#D3D3D3", linetype = "dashed") +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  geom_text(aes(label = Total, 
                y = Total + 2),
            position = position_dodge(width = 0.2), 
            size = 4, color = "black") +
  coord_flip() +
  #theme(axis.text.x = element_text(angle = 90)) +  
  #theme(legend.position = "bottom", 
  #        axis.text.x = element_blank(),
  #        axis.ticks.x = element_blank()) + 
  labs(title = "COVID-19 SR",
       subtitle = "Number of new cases by Date {closest_state}",
       caption = "data from: https://data.gov.rs",
       x = "towns", y = "no new cases") +
  theme_bw() +
  scale_colour_brewer(palette = "Spectral") +
  #scale_fill_distiller()
  #  theme_light(base_size = 12) +
  #  scale_fill_brewer(palette="Dark2") + 
  guides(fill = FALSE) +
  scale_y_continuous(labels = waiver(), limits = c(0, maxT+3)) +
  transition_states(Date, 1, 3, wrap = FALSE) +
  ease_aes('quadratic-in-out')
```  

---
